### ISSUE TITLE
Timed Out

### ISSUE THREAD

**Issue by maciasdev115** [anderscripts/FiveM_Queue#17]
Server is not full, but still when, they're joining, "Timed Out" is showing up. Any clue?

**Comment by anderscripts** [comment]
Look in the configuration.cfg file for this
` The number of minutes allowed for accounts to load into the game before we consider their game frozen and drop them. 
 Any account that is dropped in this use case is given grace to reconnect again within the number of minutes configured in q_reconnect_grace_time_limit.

set q_loading_time_limit 2`

The default is set to 2 minutes, if it takes longer for new players to load into your server due to number of resources and custom assets you should adjust this to give them more time.
