### ISSUE TITLE
Memory leaking (Slowly)

### ISSUE THREAD

**Issue by mickeygeecom** [anderscripts/FiveM_Queue#2]
I'll just add it. I guess you're well aware of this issue - else very good job on this ressource!
Will test it again when memory-leaking is sorted.

**Comment by anderscripts** [comment]
Tested for memory leaks, all referenced objects are handled by GC once fully removed from session.  Objects persist in memory as long as they persist in the List<SessionAccounts>.  Objects in other lists such as Priority and Reserved will persist through the server session because they are used in add/remove/join methods.  There are other optimizations planned for future updates to improve performance but memory leaking should not be an issue currently.
