### ISSUE TITLE
/q_addpriority added to offlinepriority.json

### ISSUE THREAD

**Issue by bathorus** [anderscripts/FiveM_Queue#22]
Hi, i was trying to add priority to a player, but it is added to offlinepriority.json, and the player is still not set to priority. is there anything that i missed?

**Comment by anderscripts** [comment]
If the player was in queue when priority was added they need to cancel and rejoin the queue for it to pickup the priority change.

If the player was completely offline when you ran the command and they were not given priority after joining I would check to make sure you inputted the correct license or steam as the parameter because it likely does not match if this was the case.

**Comment by bathorus** [comment]
hi thanks for the response @anderscripts ,

there's another question, i got this error
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
Unhandled exception in Mono script environment: System.NullReferenceException: Object reference not set to an instance of an object (null)GlobaAborted (core dumped)
```
is this error caused by fivemqueue? since the only script that i installed using C# is only fivemqueue.

**Comment by anderscripts** [comment]
It shouldn't be caused by the queue resource, I have everything wrapped in error catching so if any error happens it prints to the server console as a debug with custom text like this.

This example would be if an error occurred in the function called SteamProfileToHex()

[fivemqueue - ERROR] - SteamProfileToHex()
