### ISSUE TITLE
Queue 128 Slots

### ISSUE THREAD

**Issue by Smiling2death** [anderscripts/FiveM_Queue#30]
Your Queue script is not working for 128 slots. The limit is 64.

Is it possible to update this?

Thanks in advance

**Comment by Smiling2death** [comment]
Solved it by changing this line:
 if (newMax <= 0 || newMax > 64) { Debug.WriteLine($"changemax must be between 1 and 64"); return; }
into
 if (newMax <= 0 || newMax > 128) { Debug.WriteLine($"changemax must be between 1 and 128"); return; }

Tested it on a live server and works flawless.

**Comment by anderscripts** [comment]
The code you pasted is very specifically used by a command that is issued via rcon.  Since the OneSync 64 update I made so long as the server is launched with one sync enabled the configuration setting for set q_max_session_slots can be as high as you need it to be, there is no upper limit for any one sync enabled server to avoid needing to change this multiple times as FiveM moves from 64 to 128 to 256 or whatever.  The only limit is imposed on servers launched without one sync enabled which is 32.
