### ISSUE TITLE
Changing server name to default FXServer

### ISSUE THREAD

**Issue by cshonza** [anderscripts/FiveM_Queue#37]
Hello,
I use your connect queue script, but when i use that script it changes server name to: "default FXServer" and it write number of connected players in queue before it, where is the problem?

**Comment by anderscripts** [comment]
The problem is happening likely because you have set your server name in your server.cfg file after you have started the queue resource.  Server config stuff should be done prior to starting resources.

If you don't want to add the queue counter at all to the server name this is controlled in the resources __configuration.cfg file, set both of these back to false.

```
# Add the queue and priority queue count at the start of the server name
set q_add_queue_count_before_server_name "false"


# Add the queue and priority queue count at the end of the server name
set q_add_queue_count_after_server_name "false"
```
